disabled_rules:
  - identifier_name
  - type_name
  - nesting
  - line_length
  - function_body_length
  - cyclomatic_complexity
  - large_tuple
  - file_length
  - type_body_length

included: 
  - Sources
  - Tests
